### ISSUE TITLE
Add a formal parser for * micro expressions

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_ast#15]
From https://github.com/dart-lang/angular_ast/pull/12#discussion_r93811712:

> I think `:` is allowed more than just here, ie `let x of: items`.
> 
> Also, I think `let x of items` is equivalent to `let x; of items`
> 
> In general I think the grammar is pretty simple:
> 
> ```
> Star := '*' name '=' '"' (expr | MicroExprList) '"'
> MicroExprList = (LetExpr | BindExpr)+
> LetExpr := 'let' id ('=' id)? ';'?
> BindExpr := (id ':'?)? expr ';'?
> ```
> 
> Even simpler when you think of `*x="y"` as sugar for `template="x y"`
> 
> ```
> Template := 'template' '=' '"' MicroExprList '"'
> ```

**Comment by MichaelRFairhurst** [comment]
this is BNF by the way (kind of like regexps)
