### ISSUE TITLE
Changing Lexer and Parser to be no longer factory const.

### ISSUE THREAD

**Issue by mk13** [dart-lang/angular_ast#20]
This is a pretty significant change in terms of architecture and wanted to discuss this before submitting a PR on it. 

Is there a strong reason to keep the Lexer and Parser as const factories? I would like to change it to just regular constructor. 

TL;DR reason: Current parser, upon seeing a parse error, gives up and throws a single error. I want to recover from predictable parse errors and continue parsing the document while also throwing further parse errors it sees.

I want the NgScanner to store all propagated errors in a list, which can be accessed by the NgLexer. Since NgLexer is a const and holds no real value (unless static - but that's a bad idea), I can't propagate errors into NgLexer. Similar issue with the NgParser.

**Comment by zoechi** [comment]
Just an idea. If this change has strong disadvantages, also an Expando can be used to attach data to const instances.

**Comment by matanlurey** [comment]
I'm OK with both of these changes. If we want to ever have a "mode" of the Lexer / Parser that was fail fast and const, I can always add it back in with an interface of some sort. SGTM @mk13

**Comment by mk13** [comment]
Thanks for the response! I'll do some experimentation to see what would be the best steps moving forward, but good to know it's okay to change this.

**Comment by matanlurey** [comment]
In general if you or @MichaelRFairhurst need something changed, feel free to propose it. My only main concern will likely be if it makes the public API much more confusing for the common case or if it will cause performance regressions for the compiler (i.e. non-interactive clients).
