### ISSUE TITLE
Legacy method type annotations for `TemplateAst.accept`

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/angular_ast#39]
Currently the method signature of `TemplateAst.accept` is

```dart
/*=R*/ accept/*<R, C>*/(TemplateAstVisitor/*<R, C>*/ visitor, [C context]);
```

Any reason why it's not?

```dart
R accept<R, C>(TemplateAstVisitor<R, C> visitor, [C context]);
```

**Comment by mk13** [comment]
I'm not 100% sure, but I think this was done because the second format wasn't fully supported when originally written. Ping @matanlurey; can you verify?

**Comment by matanlurey** [comment]
We can clean this up, it was just due to generics not being rolled out first. PRs are welcome :)

**Comment by mk13** [comment]
Great, will clean it up, unless you want to take it @daniel-v ?

**Comment by daniel-v** [comment]
I'll take it. :)
