### ISSUE TITLE
Multi line attribute values not supported

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_ast#52]
https://github.com/dart-lang/angular_analyzer_plugin/issues/401

**Comment by matanlurey** [comment]
I'd argue this is WAI, and the compiler probably shouldn't be handling it.

That being said, for backwards compatibility, let's just do it.

**Comment by zoechi** [comment]
At least in TS it was all about just supporting valid HTML and line breaks in HTML are not valid in attribute values.

**Comment by LorenVS** [comment]
I've updated [dart-lang/angular_analyzer_plugin#401](https://github.com/dart-lang/angular_analyzer_plugin/issues/401). I believe I incorrectly reported this issue, and multiline attributes are already supported

**Comment by mk13** [comment]
Closing this ticket then; reopen if it's still a persistent issue.
