### ISSUE TITLE
Improve error message for * on <template> element

### ISSUE THREAD

**Issue by MichaelRFairhurst** [dart-lang/angular_ast#62]
Currently using the `*` sytnax on a `<template>` element like

```html
<template *ngIf="condition">
```

produces the error message

> Invalid decorator in 'template' element

Providing a link to the[ `*` documentation](https://webdev.dartlang.org/angular/guide/structural-directives#the-asterisk--prefix) could be more helpful for new users.

Originally filed here: https://github.com/dart-lang/angular_analyzer_plugin/issues/451

**Comment by alorenzen** [comment]
Since this repository is deprecated in favor of the angular mono-repo, should we move this issue there?

**Comment by MichaelRFairhurst** [comment]
Ah, didn't realize this repository is deprecated.

Where's the active one?

**Comment by alorenzen** [comment]
https://github.com/dart-lang/angular/tree/master/angular_ast

Not sure if we have a label yet for angular_ast specific issues, but we can certainly make one.

**Comment by MichaelRFairhurst** [comment]
https://github.com/dart-lang/angular/issues/687
